@startuml
set namespaceSeparator none
class "Studijní program" {
  "kód": string
}

class "Věc" {
}

class "Téma dizertační práce" {
  "aktuálně nabízeno": boolean
  "kontext tématu dizertační práce": text
  "doporučovaná pracoviště obecně": text
}

class "Výzkumné pracoviště" {
  orjk: string
}

"Věc" <|-- "Studijní program"
"Studijní program" -- "Téma dizertační práce" :  "má studijní program"
"Téma dizertační práce" -- "Výzkumné pracoviště" :  "má konkrétní doporučované pracoviště"
@enduml
