// <auto-generated />
using System;
using DataSpecificationNavigationBackend.ConnectorsLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSpecificationNavigationBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250720160534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("DataspecNavigationHelper.Model.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSpecificationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSpecificationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.DataSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataspecerPackageUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSpecifications");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.DataSpecificationItem", b =>
                {
                    b.Property<string>("Iri")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataSpecificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Iri", "DataSpecificationId");

                    b.HasIndex("DataSpecificationId");

                    b.HasIndex("MessageId");

                    b.ToTable("DataSpecificationItems");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.Conversation", b =>
                {
                    b.HasOne("DataspecNavigationHelper.Model.DataSpecification", "DataSpecification")
                        .WithMany()
                        .HasForeignKey("DataSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSpecification");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.DataSpecificationItem", b =>
                {
                    b.HasOne("DataspecNavigationHelper.Model.DataSpecification", "DataSpecification")
                        .WithMany()
                        .HasForeignKey("DataSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataspecNavigationHelper.Model.Message", null)
                        .WithMany("RelatedItems")
                        .HasForeignKey("MessageId");

                    b.Navigation("DataSpecification");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.Message", b =>
                {
                    b.HasOne("DataspecNavigationHelper.Model.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DataspecNavigationHelper.Model.Message", b =>
                {
                    b.Navigation("RelatedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
