PREFIX ns1: <https://slovník.gov.cz/generický/věda-a-výzkum/pojem/>
PREFIX ns2: <https://slovník.gov.cz/datový/školství/pojem/>
SELECT (?v2 AS ?currently_offered) (?v3 AS ?recommended_workplaces_in_general) (?v4 AS ?the_context_of_the_dissertation_topic) (?v6 AS ?has_a_study_program_code) (?v8 AS ?has_a_specific_recommended_workplace_orjk)
WHERE {
  ?v1 a ns1:téma-dizertační-práce .
  OPTIONAL {
    ?v1 ns1:aktuálně-nabízeno ?v2 .
  }
  OPTIONAL {
    ?v1 ns1:doporučovaná-pracoviště-obecně ?v3 .
  }
  OPTIONAL {
    ?v1 ns1:kontext-tématu-dizertační-práce ?v4 .
  }
  OPTIONAL {
    ?v5 a ns2:studijní-program .
    OPTIONAL {
      ?v5 ns2:kód ?v6 .
    }
    ?v1 ns1:má-studijní-program ?v5 .
  }
  OPTIONAL {
    ?v7 a ns1:výzkumné-pracoviště .
    OPTIONAL {
      ?v7 ns1:orjk ?v8 .
    }
    ?v1 ns1:má-konkrétní-doporučované-pracoviště ?v7 .
  }
}
